/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizz_buzz;

public class FizzBuzz {
    public static String fizz(int[] input) {
        StringBuffer result = new StringBuffer();
        for(int x : input) {
            if(x%3 == 0 && x%5 == 0) {
                result.append("fizzBuzz");
            } else if(x%3 == 0) {
                result.append("fizz");
            } else if(x%5 == 0) {
                result.append("buzz");
            } else {
                result.append(x);
            }
            if(input.length > 1) {
                result.append(" ");
            }
        }
        return result.toString();
    }
}
