/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizz_buzz;

import org.junit.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class FizzBuzzTest {
    @Test
    public void fizzForFactorsOfThree() {
        int[] input = {3};

        String result = FizzBuzz.fizz(input);

        assertThat(result, is("fizz"));
    }

    @Test
    public void buzzForFactorsOfFive() {
        int[] input = {5};

        String result = FizzBuzz.fizz(input);

        assertThat(result, is("buzz"));
    }

    @Test
    public void fizzBuzzForFactorsOfThreeAndFive() {
        int[] input = {15};

        String result = FizzBuzz.fizz(input);

        assertThat(result, is("fizzBuzz"));
    }

    @Test
    public void theNumberWhenNotAFactorOfThreeOrFive() {
        int[] input = {1};

        String result = FizzBuzz.fizz(input);

        assertThat(result, is("1"));
    }

    @Test
    public void handlesAllTheNumbers() {
        int[] input = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25};

        String result = FizzBuzz.fizz(input);

        assertThat(result, is("1 2 fizz 4 buzz fizz 7 8 fizz buzz 11 fizz 13 14 fizzBuzz 16 17 fizz 19 buzz fizz 22 23 fizz buzz "));
    }
}
